---

- hosts: digitalocean
  roles:
    - { role: init, become: true }
    - { role: php, become: true }
    - { role: nodejs, become: true }
    - { role: composer, become: true }
    - { role: nginx, become: true }
    - { role: mysql, become: true }
    - { role: cleanup, become: true }
    - { role: clone, become: true }
    - { role: build, become: true }
    - { role: migrations, become: true }
    - { role: activate, become: true }
    