---

- hosts: digitalocean
  tasks:
  - name: Look for Previous Releases
    shell: "ls -t {{ projects_root }}/{{ project_name }}/releases | head -2 | tail -1"
    register: directory

  - name: Rollback
    become: yes
    shell: ln -sfn "{{ projects_root }}/{{ project_name }}/releases/{{ item }}" "{{ projects_root }}/{{ project_name }}/current"
    with_items: "{{ directory.stdout_lines }}"
    