---

- name: Check if current folder exists
  stat:
    path: "{{ projects_root }}/{{ project_name }}/current"
  register: current_dir

- name: Remove current folder (on first release)
  file:
    state: absent
    path: "{{ projects_root }}/{{ project_name }}/current"
  when: current_dir.stat.isdir is defined and current_dir.stat.isdir

- name: Relink to New Release
  file:
    state: link
    path: "{{ projects_root }}/{{ project_name }}/current"
    src: "{{ projects_root }}/{{ project_name }}/releases/{{ release_folder }}"
    force: yes

- name: Copy .env.example ===> shared/.env
  copy:
    remote_src: yes
    src: "{{ projects_root }}/{{ project_name }}/releases/{{ release_folder }}/.env.example"
    dest: "{{ projects_root }}/{{ project_name }}/shared/.env"
    force: no

- name: Use Shared .env file
  file:
    state: link
    path: "{{ projects_root }}/{{ project_name }}/releases/{{ release_folder }}/.env"
    src: "{{ projects_root }}/{{ project_name }}/shared/.env"
    force: yes