---

- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: Install Composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: Rename Binary
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Apply Executable Permissions
  file: 
    path: /usr/local/bin/composer
    mode: a+x
    state: file
