---

- name: Add PHP 7 PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install PHP CLI
  apt:
    name: php7.1-cli
    state: latest

- name: Install PHP FPM
  apt:
    name: php7.1-fpm
    state: latest

- name: Install Common PHP Extensions
  apt:
    name: [ 'php7.1-xml', 'php7.1-mbstring', 'php7.1-mysql' ]
    state: latest
  notify:
    - Restart PHP-FPM
